import type { Metadata } from 'next';
import { Inter, Josefin_Sans, Urbanist } from 'next/font/google';
import './globals.css';
import { AppProvider } from '@/providers/AppProvider';
import Header from '@/components/Layout/Header/Header';
import Footer from '@/components/Layout/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });
const josefin_sans = Josefin_Sans({ subsets: ['latin'] });
const urbanist = Urbanist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${josefin_sans.className} ${urbanist.className}`}
      >
        <AppProvider>
          <Header />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
