import type { Metadata } from 'next';
import { Josefin_Sans, Urbanist } from 'next/font/google';
import './globals.css';
import { AppProvider } from '@/providers/AppProvider';
import Header from '@/components/Layout/Header/Header';
import Footer from '@/components/Layout/Footer/Footer';

const josefin_sans = Josefin_Sans({
  subsets: ['latin'],
  variable: '--font-josefin',
});
const urbanist = Urbanist({ subsets: ['latin'], variable: '--font-urbanist' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${josefin_sans.variable} ${urbanist.variable}`}>
      <body>
        <AppProvider>
          <Header />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
