name: Node.js CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.11.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn run build
    - run: pm2 delete nextjs-app || true
    - run: pm2 start npm --name nextjs-app -- run start -- -p 3000