name: CI/CD - Update Next.js app on AWS

on:
  push:
    branches: [main]

jobs:
  update-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js app
        run: yarn run build

      - name: SSH into EC2 instance (replace with your details)
        uses: ttnsk1/run-on-aws@v1.4.0
        with:
          aws-region: us-east-1
          instance-id: i-02e9039ce25c3757b
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          commands:
            - cd /landing-page # Replace with your app directory
            - yarn install # Install dependencies
            - yarn run build # Build the Next.js app
            - pm2 stop nextjs-app # Replace with your app name
            - pm2 delete nextjs-app # Replace with your app name
            - ppm2 start npm --name nextjs-app -- run start -- -p 3000 # Start the new app
