name: CI/CD - Next.js App

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Adjust OS if needed
    steps:
      - uses: actions/checkout@v3 # Checkout code from repository
      - name: Use AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - name: SSH into EC2 instance (replace with your details)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
      - name: Navigate to project directory
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd landing-page"
      - name: Install dependencies
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "yarn install"
      - name: Build Next.js app
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "yarn run build"
      - name: Restart pm2 process (adjust as needed)
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "yarn run start"  
