name: CI/CD - Next.js App

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Adjust OS if needed
    steps:
      - uses: actions/checkout@v3 # Checkout code from repository

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          
      - name: nstall Yarn
        run: npm install -g yarn
        
      
      - name: Use AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - name: SSH into EC2 instance (replace with your details)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
           cd ~/landing-page
           yarn install
           yarn run build
           yarn run start